AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - '.git/**/*'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Metrics/MethodLength:
  Max: 70

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Max: 200

Lint/EmptyBlock:
  Enabled: false

Metrics/BlockNesting:
  Max: 5

Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
